; Target asset paths. These assets must first be created in Unreal Editor.
[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/L_Opening.L_Opening
GameDefaultMap=/Game/Maps/L_Opening.L_Opening
GlobalDefaultGameMode=/Game/Blueprints/Core/BP_GameModeBase.BP_GameModeBase_C
GameInstanceClass=/Game/Blueprints/Core/BP_GameInstance.BP_GameInstance_C
